# Generated by Django 5.1.5 on 2025-03-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
